### ISSUE TITLE
Converting existing composition: default values

### ISSUE THREAD

**Issue by Smana** [upbound/function-patch-and-transform#2]
### What happened?

I'm evaluating this function to convert an existing one with built-in patching method.
However I'm facing this error and I don't really understand why.

```console
status:
  conditions:
  - lastTransitionTime: "2023-11-23T14:17:53Z"
    message: 'cannot compose resources: pipeline step "patch-and-transform" returned
      a fatal result: invalid Function input: resources[3].patches[3].transforms[0].string.type:
      Required value: string transform type is required'
```

Having a look to [my composition](https://github.com/Smana/demo-secured-eks/blob/harbor_functions/infrastructure/base/crossplane/configuration/sql-instance-composition.yaml#L135) it is actually there. And to be precise all the `transforms` statements have a type.

```yaml
              - fromFieldPath: metadata.uid
                toFieldPath: spec.writeConnectionSecretToRef.name
                transforms:
                  - type: string
                    string:
                      fmt: "%s-sql"
```

Am I missing something?

### What environment did it happen in?
Kubernetes version: v1.28.3-eks-4f4795d
Crossplane version: 1.14.2
Function version: v0.2.1

**Comment by Smana** [comment]
I think I get it based on the documentation:
```yaml
      transforms:
      - type: string
        string:
          type: Format
          fmt: '{"kubernetes.io/cluster/%s": "true"}'
```
Maybe there's a default value for the native patching methode. Trying that!
